export const data = [
  {
    id: 1,
    name: "Big Knife",
    Location: "Mombasa rd. kobil petrol station",
    openingHours: "7am-9pm",
    website: "www.bigKnife.com",
    phoneNumber: 555555555,
    category: "Turkey",
    image: require("../src/images/kfc.jpeg"),
  },
  {
    id: 2,
    name: "Teriyaki chicken",
    Location: "CBD,Haile sealsie avenue",
    openingHours: "7am-9pm",
    website: "www.teriyaki.com",
    phoneNumber: 666666555,
    category: "Japannesse",
    image: require("../src/images/rest.jpg"),
  },
  {
    id: 3,
    name: "Kilimanjaro Food Court",
    Location: "CBD,Moi avenue",
    openingHours: "7am-9pm",
    website: "www.Kilimanjaro.com",
    phoneNumber: 666666555,
    category: "contemprary",
    image: require("../src/images/humburger.jpg"),
  },
  {
    id: 4,
    name: "Beirut",
    Location: "CBD,mama ngina street",
    openingHours: "7am-9pm",
    website: "www.Beirut.com",
    phoneNumber: 666666555,
    category: "Arab",
    image: require("../src/images/beirut.jpeg"),
  },
  {
    id: 5,
    name: "Taste of China",
    Location: "12th floor TRV Parkwest Office Suites",
    openingHours: "7am-9pm",
    website: "www.toc.com",
    phoneNumber: 666666555,
    category: "Chinnesse",
    image: require("../src/images/china.jpg"),
  },
  {
    id: 6,
    name: "Thai chi",
    Location: "Kimathi St, Nairobi City",
    openingHours: "7am-9pm",
    website: "www.thaichi.com",
    phoneNumber: 666666555,
    category: "Thailand",
    image: require("../src/images/thai.jpg"),
  },
  {
    id: 7,
    name: "Carnivore",
    Location: "Langata",
    openingHours: "7am-9pm",
    website: "www.Kilimanjaro.com",
    phoneNumber: 666666555,
    category: "contemprary",
    image: require("../src/images/humburger.jpg"),
  },
  {
    id: 8,
    name: "Taj Sultan",
    Location: "South C",
    openingHours: "7am-9pm",
    website: "www.Kilimanjaro.com",
    phoneNumber: 666666555,
    category: "Arab",
    image: require("../src/images/humburger.jpg"),
  },
];
